### ISSUE TITLE
librispeech dataset problem

### ISSUE THREAD

**Issue by ruby11dog** [zhang-wy15/Attack_practical_asv#1]
the organization of librispeech dataset is different from your code, it  consists of flac file, is there a script to convert the dataset into the organization you use in your code?

**Comment by zhang-wy15** [comment]
> the organization of librispeech dataset is different from your code, it consists of flac file, is there a script to convert the dataset into the organization you use in your code?

You can use ```sox``` to covert flac file to wav file.

**Comment by ruby11dog** [comment]
> > the organization of librispeech dataset is different from your code, it consists of flac file, is there a script to convert the dataset into the organization you use in your code?
> 
> You can use `sox` to covert flac file to wav file.

copy, thx.
